---
- hosts: localhost
  tasks: 
  - copy: 
     content: "{{ ansible_hostname }} {{ ansible_memtotal_mb }} {{ ansible_default_ipv4.address }} {{ ansible_default_ipv4.macaddress }} {{ ansible_distribution }}"
     dest: /root/inventory.mayank 
