---
- hosts: localhost
  tasks:  
  - yum: 
     name: httpd
     state: present
    when: ansible_distribution  == 'RedHat'
  - apt: 
     name: apache2
     state: present
    when: ansible_distribution == 'Ubuntu'
